default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: web
  password: 123
  pool: 5

development:
  <<: *default
  database: myapp_development


test:
  <<: *default
  database: myapp_test
